const carsObj = {
  Honda: {
    Civic: {
      model_2020: {
        name: "Civic",
        model: 2020,
        price: "PRK 1.3 crore",
        city: "Karachi",
        img: "./assets/img/Civic.png",
        color: ["Red", "White", "Blue", "Green"],
      },
      model_2021: {
        name: "Civic",
        model: 2021,
        price: "PKR 36.5 lacs",
        city: "Hyderabad",
        img: "./assets/img/Civic.png",
        color: ["Red", "White", "Gray"],
      },
      model_2022: {
        name: "Civic",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Civic.png",
        color: ["Red", "White", "Blue", "Black"],
      },
    },
    City: {
      model_2020: {
        name: "City",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Honda_City_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "City",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Honda_City_Front.jpg",
        color: ["Red", "White", "Gray"],
      },
      model_2022: {
        name: "City",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Honda_City_Front.jpg",
        color: ["Blue", "Gray", "Black"],
      },
    },
    HondaFit: {
      model_2020: {
        name: "Honda Fit",
        model: 2020,
        price: "PKR 29.5 lacs",
        city: "Karachi",
        img: "./assets/img/Honda-Fit.png",
        color: ["Blue", "Silver", "Red"],
      },
      model_2021: {
        name: "Honda Fit",
        model: 2021,
        price: "PKR 16.5 lacs",
        city: "Islamabad",
        img: "./assets/img/Honda-Fit.png",
        color: ["Red", "White", "Gray", "Blue"],
      },
      model_2022: {
        name: "Honda Fit",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Honda-Fit.png",
        color: ["Yellow", "Black"],
      },
    },
    HondaHRV: {
      model_2020: {
        name: "Honda HRV",
        model: 2020,
        price: "PKR 95.5 lacs",
        city: "Multan",
        img: "./assets/img/hr-v.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Honda HRV",
        model: 2021,
        price: "PKR 66.5 lacs",
        city: "Karachi",
        img: "./assets/img/hr-v.png",
        color: ["Red", "White", "Gray"],
      },
      model_2022: {
        name: "Honda HRV",
        model: 2022,
        price: "PKR 76.5 lacs",
        city: "Multan",
        img: "./assets/img/hr-v.png",
        color: ["Blue", "Gray", "Black"],
      },
    },
    HondaFreed: {
      model_2020: {
        name: "Honda Freed",
        model: 2020,
        price: "PKR 86.5 lacs",
        city: "Hyderabad",
        img: "./assets/img/honda-freed-price.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Honda Freed",
        model: 2021,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/honda-freed-price.webp",
        color: ["Red", "White", "Gray"],
      },
      model_2022: {
        name: "Honda Freed",
        model: 2022,
        price: "PKR 96.5 lacs",
        img: "./assets/img/honda-freed-price.webp",
        color: ["Blue", "Gray", "Black"],
      },
    },
    HondaCRZ: {
      model_2020: {
        name: "Honda CRZ",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/honda-crz.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Honda CRZ",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/honda-crz.webp",
        color: ["Red", "White", "Gray"],
      },
      model_2022: {
        name: "Honda CRZ",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/honda-crz.webp",
        color: ["Blue", "Gray", "Black"],
      },
    },
  },
  Toyota: {
    Corolla: {
      model_2020: {
        name: "Corolla",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/attitude-black.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Corolla",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/attitude-black.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Corolla",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/attitude-black.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    ToyotaCamry: {
      model_2020: {
        name: "Toyota Camry",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/toyota-camera.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Toyota Camry",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/toyota-camera.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Toyota Camry",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/toyota-camera.webp",
        color: ["Silver", "Black", "Red"],
      },
    },
    Prius: {
      model_2020: {
        name: "Prius",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Prius-ST-Steel-Blue-metallic.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Prius",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Prius-ST-Steel-Blue-metallic.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Prius",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Prius-ST-Steel-Blue-metallic.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    Yaris: {
      model_2020: {
        name: "Yaris",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/toyota-yaris.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Yaris",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/toyota-yaris.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Yaris",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/toyota-yaris.webp",
        color: ["Silver", "Black", "Red"],
      },
    },
    ToyotaFortuner: {
      model_2020: {
        name: "Toyota Fortuner",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/fortuner.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Toyota Fortuner",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/fortuner.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Toyota Fortuner",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/fortuner.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    Rav4: {
      model_2020: {
        name: "Rav4",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/2019-Toyota-RAV4-Hero-Image-CA.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Rav4",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/2019-Toyota-RAV4-Hero-Image-CA.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Rav4",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/2019-Toyota-RAV4-Hero-Image-CA.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    ToyotaCHR: {
      model_2020: {
        name: "Toyota-CHR",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/c-hr.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Toyota-CHR",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/c-hr.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Toyota-CHR",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/c-hr.jpg",
        color: ["Silver", "Black", "Red"],
      },
    },
    HiAce: {
      model_2020: {
        name: "HiAce",
        model: 2020,
        img: "./assets/img/HIACE.jpg",
        price: "PKR 54.5 lacs",
        city: "Multan",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "HiAce",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/HIACE.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "HiAce",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/HIACE.jpg",
        color: ["Silver", "Black", "Red"],
      },
    },
  },
  Suzuki: {
    SuzukiSwift: {
      model_2020: {
        name: "Suzuki Swift",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Swift_GL.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Suzuki Swift",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Swift_GL.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Suzuki Swift",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Swift_GL.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    SuzukiJimny: {
      model_2020: {
        name: "Suzuki Jimny",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Jimny.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Suzuki Jimny",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Jimny.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Suzuki Jimny",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Jimny.webp",
        color: ["Silver", "Black", "Red"],
      },
    },
    SuzukiAlto: {
      model_2020: {
        name: "Suzuki Alto",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/alto-ban.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Suzuki Alto",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/alto-ban.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Suzuki Alto",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/alto-ban.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    SuzukiIgnis: {
      model_2020: {
        name: "Suzuki Ignis",
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/suzuki_ignis.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Suzuki Ignis",
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/suzuki_ignis.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Suzuki Ignis",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/suzuki_ignis.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    SuzukiVitara: {
      model_2020: {
        name: "Suzuki Vitara",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/SuzukiVitara.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Suzuki Vitara",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/SuzukiVitara.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Suzuki Vitara",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/SuzukiVitara.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    SuzukiCultus: {
      model_2020: {
        name: "Suzuki Cultus",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/SuzukiCultus.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Suzuki Cultus",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/SuzukiCultus.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Suzuki Cultus",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/SuzukiCultus.webp",
        color: ["Silver", "Black", "Red"],
      },
    },
  },
  Proton: {
    ProtonSaga: {
      model_2020: {
        name: "Proton Saga",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Proton Saga",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Proton Saga",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
    },
    ProtonPersona: {
      model_2020: {
        name: "ProtonPersona",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "ProtonPersona",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "ProtonPersona",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
    },
    ProtonExora: {
      model_2020: {
        name: "ProtonExora",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "ProtonExora",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "ProtonExora",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
    },
    ProtonX70: {
      model_2020: {
        name: "ProtonX70",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "ProtonX70",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "ProtonX70",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
    },
    ProtonIriz: {
      model_2020: {
        name: "Proton Iriz",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Proton Iriz",
        model: 2020,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Proton Iriz",
        model: 2020,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Proton_Saga_Front.jpg",
        color: ["Silver", "Black", "Red"],
      },
    },
  },
  KIA: {
    KiaSportage: {
      model_2020: {
        name: "Kia Sportage",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Sportage.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Kia Sportage",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Sportage.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Kia Sportage",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Sportage.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    KiaSorento: {
      model_2020: {
        name: "Kia Sorento",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/Kia-Sorento.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Kia Sorento",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/Kia-Sorento.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Kia Sorento",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/Kia-Sorento.webp",
        color: ["Silver", "Black", "Red"],
      },
    },
    KiaSeltos: {
      model_2020: {
        name: "Kia Rio",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/kia-seltos-aurora-black.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Kia Rio",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/kia-seltos-aurora-black.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Kia Rio",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/kia-seltos-aurora-black.png",
        color: ["Silver", "Black", "Red"],
      },
    },
    KiaRio: {
      model_2020: {
        name: "Kia Rio",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/kia-rio.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Kia Rio",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/kia-rio.webp",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Kia Rio",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/kia-rio.webp",
        color: ["Silver", "Black", "Red"],
      },
    },
    KiaPicanto: {
      model_2020: {
        name: "Kia Picanto",
        model: 2020,
        price: "PKR 54.5 lacs",
        city: "Multan",
        img: "./assets/img/KIA_Picanto.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2021: {
        name: "Kia Picanto",
        model: 2021,
        price: "PKR 31.5 lacs",
        city: "Lahore",
        img: "./assets/img/KIA_Picanto.png",
        color: ["Silver", "Black", "Red"],
      },
      model_2022: {
        name: "Kia Picanto",
        model: 2022,
        price: "PKR 36.5 lacs",
        city: "Karachi",
        img: "./assets/img/KIA_Picanto.png",
        color: ["Silver", "Black", "Red"],
      },
    },
  },
};

export { carsObj };
